apiVersion: v1
kind: Pod
metadata:
  name: pod-with-host-access-and-volume
spec:
  containers:
  - name: host-access-container
    image: your-image
    securityContext:
      privileged: true
    volumeMounts:
    - name: host-volume
      mountPath: /host-data
  volumes:
  - name: host-volume
    hostPath:
      path: /path/on/host